#!/bin/bash
pyrdkit=/opt/anaconda/envs/_test/bin/python
#
# create energies file
#
cd "$1"
grep "FINAL HEAT" *+*.out > "$1".energies
grep "CURRENT VALUE" *+*.out >> "$1".energies
grep "CURRENT BEST" *+*.out >> "$1".energies
grep -v "GEOMETRY" "$1".energies > temp && mv temp "$1".energies
grep -v "GRADIENT" "$1".energies > temp && mv temp "$1".energies
mv "$1".energies ../.
#
# check if bonds have changed (e.g. proton transfer)
#
rm "$1"*.out
python ../moprd2.py *.out
for x in *.xyz; do babel -ixyz $x -osdf ${x%.*}.sdf; done
mkdir end_geom
mv *.sdf end_geom/.
cd ..
python readsdf.py "$1"/start_geom/*.sdf "$1"/end_geom/*.sdf
#
# find reactive centers
#
$pyrdkit lowpka4.py "$1".energies 1.0 > "$1"_1.pka
$pyrdkit lowpka4.py "$1".energies 3.0 > "$1"_3.pka
#
pyrdkit2=/home/yensen/anaconda2/envs/my-rdkit-env/bin/python
$pyrdkit2 highlight_atoms.py "$1"_1.pka
$pyrdkit2 highlight_atoms.py "$1"_3.pka
python merge_svg.py "$1"_1.svg "$1"_3.svg
