#!/bin/bash
pyrdkit=/opt/anaconda/envs/_test/bin/python
#
# creater energies file
#
cd "$1"
grep "FINAL HEAT" *+*.out > "$1".energies
grep "CURRENT VALUE" *+*.out >> "$1".energies
grep "CURRENT BEST" *+*.out >> "$1".energies
grep -v "GEOMETRY" "$1".energies > temp && mv temp "$1".energies
grep -v "GRADIENT" "$1".energies > temp && mv temp "$1".energies
mv "$1".energies ../.
#
# check if bonds have changed (e.g. proton transfer)
#
rm "$1"*.out
python ../moprd2.py *.out
for x in *.xyz; do babel -ixyz $x -osdf ${x%.*}.sdf; done
mkdir end_geom
mv *.sdf end_geom/.
cd ..
python readsdf.py "$1"/start_geom/*.sdf "$1"/end_geom/*.sdf
#
# find reactive centers
#
$pyrdkit lowpka4.py "$1".energies > "$1".pka
#
# Create svg file with highlighted atoms
#
$pyrdkit highlight_atoms.py "$1".pka
